//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotesMarketPlaceEntities8 : DbContext
    {
        public NotesMarketPlaceEntities8()
            : base("name=NotesMarketPlaceEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddEditCategory> AddEditCategories { get; set; }
        public virtual DbSet<AddEditCountry> AddEditCountries { get; set; }
        public virtual DbSet<AddEditType> AddEditTypes { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<DownloadedNote> DownloadedNotes { get; set; }
        public virtual DbSet<ManageSystemConfiguration> ManageSystemConfigurations { get; set; }
        public virtual DbSet<NoteDetail> NoteDetails { get; set; }
        public virtual DbSet<NoteReview> NoteReviews { get; set; }
        public virtual DbSet<SellerNotesAttachment> SellerNotesAttachments { get; set; }
        public virtual DbSet<SpamReportsTable> SpamReportsTables { get; set; }
        public virtual DbSet<StatusTable> StatusTables { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
