//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DownloadedNote
    {
        public int ID { get; set; }
        public int NoteID { get; set; }
        public string NoteTitle { get; set; }
        public string Category { get; set; }
        public string Buyer { get; set; }
        public string Seller { get; set; }
        public string SellType { get; set; }
        public string Price { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual NoteDetail NoteDetail { get; set; }
    }
}
