//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes_MarketPlace.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NoteDetail()
        {
            this.DownloadedNotes = new HashSet<DownloadedNote>();
            this.NoteReviews = new HashSet<NoteReview>();
            this.SellerNotesAttachments = new HashSet<SellerNotesAttachment>();
            this.SpamReportsTables = new HashSet<SpamReportsTable>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int CategoryID { get; set; }
        public int TypeID { get; set; }
        public int CountryID { get; set; }
        public int Status { get; set; }
        public string NoteTitle { get; set; }
        public string DisplayPicture { get; set; }
        public string NumberOfPages { get; set; }
        public string Description { get; set; }
        public string University { get; set; }
        public string InstituitionName { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }
        public bool IsPaid { get; set; }
        public decimal SellingPrice_USD { get; set; }
        public string NotesPreview { get; set; }
        public int ActionBy { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Spam { get; set; }
        public Nullable<int> Review { get; set; }
        public Nullable<int> Star { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AddEditCategory AddEditCategory { get; set; }
        public virtual AddEditCountry AddEditCountry { get; set; }
        public virtual AddEditType AddEditType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DownloadedNote> DownloadedNotes { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteReview> NoteReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellerNotesAttachment> SellerNotesAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamReportsTable> SpamReportsTables { get; set; }
        public virtual StatusTable StatusTable { get; set; }
    }
}
